spring.application.name=core

server.servlet.context-path=/api/v1


#server.port=8080


security.jwt.secret-key=hefuhfwerjkfeoifhoif44f43upowehdjcn43o92wiqpasojnd3p2oqwas

spring.datasource.url=jdbc:postgresql://localhost:5432/lovableDB
#spring.datasource.username=rootspring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop

#to load seed data after hibernate has initialized the tables
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode= always


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

free.plan.id=550e8400-e29b-41d4-a716-446655440000

stripe.api.key=sk_test_51Tq3vE5Jcqu0fbt117HUJQnf2klCGFRRDyarp9phyC5qfIt9k07yMihCQVKjUvK4gIppVwErhxlqybAbt1gbhWvj00eQfUtFfy

stripe.webhook.secret=whsec_1fa37838663daebd851d07e2fc35e726af87f531ffd753580d4a82a242b1cb66

# payment success/failure url to be give to stripe for redirect
payment_success_url =http://localhost:8080

payment_fail_url= http://localhost:8080/


spring.servlet.multipart.max-request-size=20MB
spring.servlet.multipart.max-file-size=5MB



#max req can occupy in tomcat server queue , after that req will get 503 , server unavailable error
server.tomcat.accept-count=100

#max worker threads on tomcat server on start
server.tomcat.threads.max=200

#200 + 10 more can be created , if request queue is full
server.tomcat.threads.min-spare=10

#eureka.client.service-url.defaultZone=http://localhost:8084/eureka/

